/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as WebhooksComplianceRouteImport } from './routes/webhooks.compliance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksComplianceRoute = WebhooksComplianceRouteImport.update({
  id: '/webhooks/compliance',
  path: '/webhooks/compliance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product/$handle': typeof ProductHandleRoute
  '/webhooks/compliance': typeof WebhooksComplianceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$handle': typeof ProductHandleRoute
  '/webhooks/compliance': typeof WebhooksComplianceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product/$handle': typeof ProductHandleRoute
  '/webhooks/compliance': typeof WebhooksComplianceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/product/$handle' | '/webhooks/compliance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/product/$handle' | '/webhooks/compliance'
  id: '__root__' | '/' | '/product/$handle' | '/webhooks/compliance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductHandleRoute: typeof ProductHandleRoute
  WebhooksComplianceRoute: typeof WebhooksComplianceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/compliance': {
      id: '/webhooks/compliance'
      path: '/webhooks/compliance'
      fullPath: '/webhooks/compliance'
      preLoaderRoute: typeof WebhooksComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductHandleRoute: ProductHandleRoute,
  WebhooksComplianceRoute: WebhooksComplianceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
